# Site settings
baseurl: 
title: SSC Testing data
email: js@ppls.io
description: > # South-South Cooperation data

# Build settings
markdown: kramdown

collections:
  ssc_data:
    output: true

prose:
  rooturl: '_ssc_data'
  metadata:
    _ssc_data:
      - name: "thematic-focus"
        field:
          element: "multiselect"
          label: "Thematic Focus"
          placeholder: "Select area(s) of focus"
          options:
            - name: "Sustainable development"
              value: "sustainable-development,"
            - name: "Resilience building"
              value: "resilience-building,"
            - name: "Inclusive and effective democratic governance"
              value: "democratic-governance,"
      - name: "type"
        field:
          element: "multiselect"
          label: "Type of action"
          placeholder: "Choose action"
          options:
            - name: "Not set"
              value: null
            - name: "Capacity Building"
              value: "cap,"
            - name: "Knowledge broker"
              value: "kno,"
            - name: "Partnership facilitator"
              value: "par,"
      - name: "location"
        field:
          element: "multiselect"
          label: "Location (country, etc)"
          placeholder: "Select location(s)"
          options:
            - name: "Angola"
              value: "ago,"
            - name: "Algeria"
              value: "dza,"
            - name: "Egypt"
              value: "egy,"
            - name: "Bangladesh"
              value: "bgd,"
            - name: "Namibia"
              value: "nam,"
            - name: "Bulgaria"
              value: "bgr,"
            - name: "Bolivia (Plurinational State of)"
              value: "bol,"
            - name: "Ghana"
              value: "gha,"
            - name: "Pakistan"
              value: "pak,"
            - name: "Prog for Palestinian People"
              value: "pal,"
            - name: "Cape Verde"
              value: "cpv,"
            - name: "Honduras"
              value: "hnd,"
            - name: "Jordan"
              value: "jor,"
            - name: "Liberia"
              value: "lbr,"
            - name: "Libyan Arab Jamahiriya"
              value: "lby,"
            - name: "Malaysia"
              value: "mys,"
            - name: "Korea, Democratic People's Republic of"
              value: "prk,"
            - name: "Tanzania (United Republic of)"
              value: "tza,"
            - name: "Botswana"
              value: "bwa,"
            - name: "Cambodia"
              value: "khm,"
            - name: "Trinidad and Tobago"
              value: "tto,"
            - name: "Paraguay"
              value: "pry,"
            - name: "UN Capital Development  Fund"
              value: "h59,"
            - name: "Saudi Arabia"
              value: "sau,"
            - name: "Lebanon"
              value: "lbn,"
            - name: "Burkina Faso"
              value: "bfa,"
            - name: "Bratislava Regional Center"
              value: "svk,"
            - name: "Mauritania"
              value: "mrt,"
            - name: "Croatia"
              value: "hrv,"
            - name: "Chile"
              value: "chl,"
            - name: "China"
              value: "chn,"
            - name: "Micronesia (Federated States of)"
              value: "fsm,"
            - name: "Jamaica"
              value: "jam,"
            - name: "Peru"
              value: "per,"
            - name: "Djibouti"
              value: "dji,"
            - name: "Guinea"
              value: "gin,"
            - name: "Uruguay"
              value: "ury,"
            - name: "Thailand"
              value: "tha,"
            - name: "Seychelles"
              value: "syc,"
            - name: "Nepal"
              value: "npl,"
            - name: "Morocco"
              value: "mar,"
            - name: "Yemen"
              value: "yem,"
            - name: "Philippines"
              value: "phl,"
            - name: "South Africa"
              value: "zaf,"
            - name: "Kiribati"
              value: "kir,"
            - name: "Romania"
              value: "rou,"
            - name: "Syrian Arab Republic"
              value: "syr,"
            - name: "Nicaragua"
              value: "nic,"
            - name: "Kazakhstan"
              value: "kaz,"
            - name: "PB/South Korea Liaison Office"
              value: "h62,"
            - name: "Niue"
              value: "niu,"
            - name: "Dominica"
              value: "dma,"
            - name: "Benin"
              value: "ben,"
            - name: "Nigeria"
              value: "nga,"
            - name: "Reg Bur Latin Amer & Carib"
              value: "h03,"
            - name: "Reg Bureau for Africa"
              value: "h01,"
            - name: "Zimbabwe"
              value: "zwe,"
            - name: "Reg Bur for Arab States"
              value: "h05,"
            - name: "Sri Lanka"
              value: "lka,"
            - name: "Guyana"
              value: "guy,"
            - name: "Costa Rica"
              value: "cri,"
            - name: "Ethiopia"
              value: "eth,"
            - name: "Dakar Regional Service Centre"
              value: "r11,"
            - name: "Niger"
              value: "ner,"
            - name: "Tokelau"
              value: "tkl,"
            - name: "Turkmenistan"
              value: "tkm,"
            - name: "Suriname"
              value: "sur,"
            - name: "Panama"
              value: "pan,"
            - name: "Chad"
              value: "tcd,"
            - name: "Georgia"
              value: "geo,"
            - name: "Montenegro"
              value: "mne,"
            - name: "Mongolia"
              value: "mng,"
            - name: "Office of Human Resources"
              value: "h18,"
            - name: "Marshall Islands"
              value: "mhl,"
            - name: "Office of the Administrator"
              value: "h13,"
            - name: "Belize"
              value: "blz,"
            - name: "BCPR"
              value: "h10,"
            - name: "Evaluation Office"
              value: "h11,"
            - name: "Afghanistan"
              value: "afg,"
            - name: "Burundi"
              value: "bdi,"
            - name: "Belarus"
              value: "blr,"
            - name: "Grenada"
              value: "grd,"
            - name: "Rwanda"
              value: "rwa,"
            - name: "Argentina"
              value: "arg,"
            - name: "Pacific Centre (PC)"
              value: "psc,"
            - name: "Tajikistan"
              value: "tjk,"
            - name: "Haiti"
              value: "hti,"
            - name: "Mexico"
              value: "mex,"
            - name: "Saint Lucia"
              value: "lca,"
            - name: "India"
              value: "ind,"
            - name: "Latvia"
              value: "lva,"
            - name: "Bhutan"
              value: "btn,"
            - name: "Saint Vincent and the Grenadines"
              value: "vct,"
            - name: "Viet Nam"
              value: "vnm,"
            - name: "Antigua and Barbuda"
              value: "atg,"
            - name: "Fiji"
              value: "fji,"
            - name: "PB/Liaison/Copenhagen"
              value: "h28,"
            - name: "Mauritius"
              value: "mus,"
            - name: "Dominican Republic"
              value: "dom,"
            - name: "PB/Liaison/Tokyo"
              value: "h25,"
            - name: "PB/Liaison/Geneva"
              value: "h24,"
            - name: "PB/Liaison/Brussels"
              value: "h27,"
            - name: "Bureau for Dev. Policy"
              value: "h21,"
            - name: "Operations Support Group"
              value: "h20,"
            - name: "PB"
              value: "h23,"
            - name: "BOM/Ofc of Asst Administrator"
              value: "h22,"
            - name: "Indonesia"
              value: "idn,"
            - name: "Vanuatu"
              value: "vut,"
            - name: "Equatorial Guinea"
              value: "gnq,"
            - name: "Democratic Republic of Congo"
              value: "cod,"
            - name: "Republic of Congo"
              value: "cog,"
            - name: "Gabon"
              value: "gab,"
            - name: "Cook Islands"
              value: "cok,"
            - name: "Comoros"
              value: "com,"
            - name: "Colombia"
              value: "col,"
            - name: "Nauru"
              value: "nru,"
            - name: "Moldova (Republic of)"
              value: "mda,"
            - name: "Madagascar"
              value: "mdg,"
            - name: "Ecuador"
              value: "ecu,"
            - name: "Senegal"
              value: "sen,"
            - name: "Maldives"
              value: "mdv,"
            - name: "Timor-Leste"
              value: "tls,"
            - name: "Lithuania"
              value: "ltu,"
            - name: "Mozambique"
              value: "moz,"
            - name: "Zambia"
              value: "zmb,"
            - name: "Gambia"
              value: "gmb,"
            - name: "Guatemala"
              value: "gtm,"
            - name: "Ukraine"
              value: "ukr,"
            - name: "Cuba"
              value: "cub,"
            - name: "Venezuela (Bolivarian Republic of)"
              value: "ven,"
            - name: "Reg Bureau for Asia & Pacific"
              value: "h04,"
            - name: "Palau"
              value: "plw,"
            - name: "Kenya"
              value: "ken,"
            - name: "Lao People's Democratic Republic"
              value: "lao,"
            - name: "Turkey"
              value: "tur,"
            - name: "Albania"
              value: "alb,"
            - name: "Tuvalu"
              value: "tuv,"
            - name: "Myanmar"
              value: "mmr,"
            - name: "Cairo Regional Center"
              value: "r44,"
            - name: "Panama Regional Center"
              value: "r46,"
            - name: "Tunisia"
              value: "tun,"
            - name: "Russian Federation"
              value: "rus,"
            - name: "Rgnl Center in Bangkok (RCB)"
              value: "brc,"
            - name: "Barbados"
              value: "brb,"
            - name: "Brazil"
              value: "bra,"
            - name: "Serbia"
              value: "srb,"
            - name: "The former Yugoslav Republic of Macedonia"
              value: "mkd,"
            - name: "Samoa"
              value: "wsm,"
            - name: "Azerbaijan"
              value: "aze,"
            - name: "Guinea-Bissau"
              value: "gnb,"
            - name: "Swaziland"
              value: "swz,"
            - name: "Tonga"
              value: "ton,"
            - name: "Côte d'Ivoire"
              value: "civ,"
            - name: "Kosovo"
              value: "kos,"
            - name: "Korea (Republic of)"
              value: "kor,"
            - name: "Central African Republic"
              value: "caf,"
            - name: "Cyprus"
              value: "cyp,"
            - name: "United Nations Volunteers"
              value: "unv,"
            - name: "Bosnia and Herzegovina"
              value: "bih,"
            - name: "Somalia"
              value: "som,"
            - name: "Uzbekistan"
              value: "uzb,"
            - name: "Cameroon"
              value: "cmr,"
            - name: "Poland"
              value: "pol,"
            - name: "Kuwait"
              value: "kwt,"
            - name: "Eritrea"
              value: "eri,"
            - name: "Togo"
              value: "tgo,"
            - name: "United Arab Emirates"
              value: "are,"
            - name: "Malawi"
              value: "mwi,"
            - name: "Iraq"
              value: "irq,"
            - name: "El Salvador"
              value: "slv,"
            - name: "Mali"
              value: "mli,"
            - name: "Sao Tome and Principe"
              value: "stp,"
            - name: "Iran (Islamic Republic of)"
              value: "irn,"
            - name: "South Sudan"
              value: "ssd,"
            - name: "Sierra Leone"
              value: "sle,"
            - name: "Saint Kitts and Nevis"
              value: "kna,"
            - name: "Bahamas"
              value: "bhs,"
            - name: "Solomon Islands"
              value: "slb,"
            - name: "Kyrgyz Republic"
              value: "kgz,"
            - name: "UN Developmt Coordination Unit"
              value: "h45,"
            - name: "Uganda"
              value: "uga,"
            - name: "Human Development Report Ofc"
              value: "h43,"
            - name: "Regional SC - Johannesburg"
              value: "rjb,"
            - name: "Lesotho"
              value: "lso,"
            - name: "Spcl Unit for South South Coop"
              value: "h42,"
            - name: "Sudan"
              value: "sdn,"
            - name: "Bahrain"
              value: "bhr,"
            - name: "Armenia"
              value: "arm,"
            - name: "Papua New Guinea"
              value: "png,"
            - name: "Ofc of Info Systems&Technology"
              value: "h48,"
      - name: "region"
        field:
          element: "multiselect"
          label: "Region"
          placeholder: "Select region"
          options:
            - name: "Latin America & Caribbean"
              value: "lac,"
            - name: "Africa"
              value: "afr,"
            - name: "Asia & Pacific"
              value: "asp,"
            - name: "Arab States"
              value: "arb,"
            - name: "Europe & CIS"
              value: "euc,"
      - name: "partners"
        field:
          element: "multiselect"
          label: "Partner types"
          options:
            - name: "International cooperation / development agencies"
              value: "int,"
            - name: "Regional / inter-governmental organizations"
              value: "reg,"
            - name: "National governments"
              value: "nat,"
            - name: "Sub-national governments"
              value: "sbn,"
            - name: "Community Support Organisations"
              value: "cso,"
            - name: "Academia"
              value: "acd,"
            - name: "Private sector"
              value: "pvt,"

