# Site settings
# baseurl: '/jekyll-data'

editor: 
  github_repo: peoplesized/ssc-dev
  url: http://prose.io

baseurl: ''
title: UNDP SSC Projects Explorer
email: js@ppls.io
description: South-South Cooperation data
host: 0.0.0.0
exclude: ['node_modules', 'Gulpfile.js', 'package.json']


# Build settings
markdown: kramdown

collections:
  ssc_data:
    output: true
