# Site settings
title: SSC Testing data
email: js@ppls.io
description: > # South-South Cooperation data
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

collections:
  ssc_data:
    output: true

prose:
  rooturl: '_ssc_data'
  metadata:
    _ssc_data:
      - name: "thematic-focus"
        field:
          element: "multiselect"
          label: "Thematic Focus"
          placeholder: "Select area(s) of focus"
          options:
            - name: "Sustainable development"
              value: "sustainable-development"
            - name: "Resilience building"
              value: "resilience-building"
            - name: "Inclusive and effective democratic governance"
              value: "democratic-governance"
      - name: "type"
        field:
          element: "select"
          label: "Type of action"
          placeholder: "Choose action"
          options:
            - name: "Unknown"
              value: "unknown"
            - name: "Capacity Building"
              value: "capacity-building"
            - name: "Knowledge broker"
              value: "knowledge-broker"
